/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StringUtils */

#ifndef _Included_StringUtils
#define _Included_StringUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StringUtils
 * Method:    reverse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StringUtils_reverse
  (JNIEnv *, jclass, jstring);

/*
 * Class:     StringUtils
 * Method:    firstNotOf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_StringUtils_firstNotOf__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     StringUtils
 * Method:    firstNotOf
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_StringUtils_firstNotOf__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     StringUtils
 * Method:    lastNotOf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_StringUtils_lastNotOf__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     StringUtils
 * Method:    lastNotOf
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_StringUtils_lastNotOf__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     StringUtils
 * Method:    generatePermuations
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_StringUtils_generatePermuations__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     StringUtils
 * Method:    generatePermuations
 * Signature: (Ljava/lang/String;I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_StringUtils_generatePermuations__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     StringUtils
 * Method:    levenshteinDistance
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_StringUtils_levenshteinDistance
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     StringUtils
 * Method:    optimalStringAlignmentDistance
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_StringUtils_optimalStringAlignmentDistance
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     StringUtils
 * Method:    damerauLevenshteinDistance
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_StringUtils_damerauLevenshteinDistance
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     StringUtils
 * Method:    boyerMooreBadChar
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_StringUtils_boyerMooreBadChar
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
